name: checkout
on: [push]

jobs:
  build:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: display local file information
        run: |
          ls -a
          git status
          git log
