name: hello
on: [push]

jobs:
  build:
    name: hello
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [world, github]
    steps:
      - name: echo
        run: echo 'hello ${{ matrix.name }}'
